name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.aircannon.AirCannon
version: ${version}
api-version: 1.13

commands:
  aircannon:
    description: "Give/reload the Air Cannon plugin"
    permission: "aircannon.command"

permissions:
  aircannon.command:
    description: "Allows access to /aircannon"
